# Generated by Django 6.0.2 on 2026-03-29 16:32

import apps.users.field_validators.phone
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=24, validators=[apps.users.field_validators.phone.PhoneValidator])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')])),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('estimated_deadline', models.DateField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_deadline', models.DateField(blank=True, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profitability', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('hour_profitability', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spent_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONCLUDED', 'Concluded'), ('PARTIALLY_CONCLUDED', 'Partially Concluded'), ('CANCELLED', 'Cancelled')], default='OPEN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('colortag', models.CharField(blank=True, max_length=7, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.project')),
            ],
        ),
    ]
