# Generated by Django 6.0.2 on 2026-03-29 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', related_query_name='address', to='projects_and_clients.client'),
        ),
        migrations.AlterField(
            model_name='clientemail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', related_query_name='email', to='projects_and_clients.client'),
        ),
        migrations.AlterField(
            model_name='clientphone',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', related_query_name='phone', to='projects_and_clients.client'),
        ),
        migrations.AlterField(
            model_name='clientrating',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', related_query_name='rating', to='projects_and_clients.client'),
        ),
    ]
