# Generated by Django 6.0.2 on 2026-05-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('projects_and_clients', '0002_alter_clientaddress_client_alter_clientemail_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='movimentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', related_query_name='task', to='finances.movimentation'),
        ),
    ]
