# Generated by Django 6.0.2 on 2026-04-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('projects_and_clients', '0003_task_description_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', related_query_name='task', to='finances.finance'),
        ),
    ]
