# Generated by Django 6.0.2 on 2026-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_clients', '0005_client_user_client_cpf_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/cover-photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='labor_fee',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=20),
            preserve_default=False,
        ),
    ]
