# Generated by Django 6.0.2 on 2026-05-10 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_clients', '0006_project_cover_photo_project_labor_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_at',
        ),
        migrations.AddField(
            model_name='task',
            name='do_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
