# Generated by Django 6.0.2 on 2026-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_clients', '0007_remove_task_done_at_task_do_at_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='do_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
