# Generated by Django 6.0.2 on 2026-05-10 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_clients', '0008_alter_task_do_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='do_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
