# Generated by Django 6.0.2 on 2026-06-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_movgroup_related_to_remove_movgroup_relation'),
        ('projects_and_clients', '0009_alter_task_do_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovGroupProjectRelation',
            fields=[
                ('pk', models.CompositePrimaryKey('mov_group', 'project', blank=True, editable=False, primary_key=True, serialize=False)),
                ('mov_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.movgroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_and_clients.project')),
            ],
        ),
    ]
