# Generated by Django 6.0.2 on 2026-06-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_clients', '0010_movgroupprojectrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
