# Generated by Django 6.0.2 on 2026-02-24 18:33

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0001_initial"),
  ]

  operations = [
    migrations.RenameField(
      model_name="user",
      old_name="name",
      new_name="username",
    ),
  ]
