# Generated by Django 6.0.2 on 2026-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0002_rename_name_user_username"),
  ]

  operations = [
    migrations.AddField(
      model_name="user",
      name="password",
      field=models.CharField(
        default="senha_admin", max_length=128, verbose_name="password"
      ),
      preserve_default=False,
    ),
  ]
