# Generated by Django 6.0.2 on 2026-02-24 20:25

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0003_user_password"),
  ]

  operations = [
    migrations.AlterModelManagers(
      name="user",
      managers=[],
    ),
    migrations.RenameField(
      model_name="user",
      old_name="username",
      new_name="name",
    ),
  ]
