# Generated by Django 6.0.2 on 2026-02-24 20:39

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("users", "0004_alter_user_managers_rename_username_user_name"),
  ]

  operations = [
    migrations.AlterModelManagers(
      name="user",
      managers=[
        ("objects", apps.users.models.UserManager()),
      ],
    ),
  ]
