# Generated by Django 6.0.2 on 2026-03-05 15:15

import apps.users.field_validators.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, validators=[apps.users.field_validators.phone.PhoneValidator]),
        ),
    ]
