# Generated by Django 6.0.2 on 2026-05-10 03:53

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models._make_profile_photo_upload_path),
        ),
    ]
