"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from datetime import timedelta

from config.env import (
  DEBUG as _DEBUG,
  DEFAULT_DB,
  DEFAULT_CACHE,
  JWT_PRIVKEY_PATH as _JWT_PRIVKEY_PATH,
  JWT_PUBKEY_PATH as _JWT_PUBKEY_PATH,
  JWT_ALGO,
  JWT_ACCESS_LIFETIME,
  JWT_REFRESH_LIFETIME,
  EMAIL_HOST as _EMAIL_HOST,
  EMAIL_PORT as _EMAIL_PORT,
  EMAIL_USE_TLS as _EMAIL_USE_TLS,
  EMAIL_HOST_USER as _EMAIL_HOST_USER,
  EMAIL_HOST_PASSWORD as _EMAIL_HOST_PASSWORD,
  DEFAULT_FROM_EMAIL as _DEFAULT_FROM_EMAIL,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@ucp)l^9ls49gyg*-c&0x#(ao&2i0_%j73w@(vw9qg0kdgnrw1"

JWT_PRIVKEY_PATH = BASE_DIR / _JWT_PRIVKEY_PATH
JWT_PUBKEY_PATH = BASE_DIR / _JWT_PUBKEY_PATH

with JWT_PRIVKEY_PATH.open("r") as f:
  JWT_PRIVKEY = f.read()

with JWT_PUBKEY_PATH.open("r") as f:
  JWT_PUBKEY = f.read()

SIMPLE_JWT = {
  "ALGORITHM": JWT_ALGO,
  "SIGNING_KEY": JWT_PRIVKEY,
  "VERIFYING_KEY": JWT_PUBKEY,
  "ACCESS_TOKEN_LIFETIME": timedelta(minutes=JWT_ACCESS_LIFETIME),
  "REFRESH_TOKEN_LIFETIME": timedelta(minutes=JWT_REFRESH_LIFETIME),
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _DEBUG

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
  "django.contrib.admin",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
  "apps.core",
  "apps.users",
  "apps.authentication",
  "apps.projects_and_clients",
]

MIDDLEWARE = [
  "django.middleware.security.SecurityMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
  "apps.core.middlewares.JWTAuthenticationMiddleware",
  "apps.core.middlewares.ValidEmailPermissionMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [BASE_DIR / "templates"],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
      ],
    },
  },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {"default": DEFAULT_DB}

CACHES = {"default": DEFAULT_CACHE}

AUTH_USER_MODEL = "users.User"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
  },
]

# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = _EMAIL_HOST
EMAIL_PORT = _EMAIL_PORT
EMAIL_USE_TLS = _EMAIL_USE_TLS
EMAIL_HOST_USER = _EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = _EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = _DEFAULT_FROM_EMAIL

# Contacts Info Validation Settings
EMAIL_VALIDATION_TOKEN_LIFETIME = timedelta(minutes=30)
EMAIL_VALIDATION_TEMPLATE = "emails/validation.html"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
