# Generated by Django 6.0.2 on 2026-05-01 18:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('related_to', models.UUIDField(blank=True, null=True)),
                ('relation', models.CharField(choices=[('NORELATION', 'No relation, personal only'), ('PROJECT', 'Project Related')], default='NORELATION', editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.CharField(choices=[('+', 'Positive - Money is comming in'), ('-', 'Negative - Money is going out')], max_length=1)),
                ('reason', models.CharField(max_length=255)),
                ('movemented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mov_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.movgroup')),
            ],
        ),
    ]
