# Generated by Django 6.0.2 on 2026-05-07 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movgroup',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='movgroup',
            name='related_to',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='movgroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_movgroup_name_unique'),
        ),
    ]
