# Generated by Django 6.0.2 on 2026-06-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_movgroup_name_alter_movgroup_related_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movgroup',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='movgroup',
            name='relation',
        ),
    ]
